# Generated by Django 5.2.1 on 2025-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('content', models.BinaryField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('publications', models.ManyToManyField(to='image_manager.gallery')),
            ],
        ),
    ]
